In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\projects\customer-churn-analysis\Customer-Churn-Records.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [9]:
df.shape

(10000, 18)

In [26]:
df.columns

Index(['CustomerId', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score',
       'Card Type', 'Point Earned', 'Age_Group', 'Credit_Score_Group',
       'Balance_Category', 'Satisfaction_Level'],
      dtype='str')

In [27]:
df.columns = df.columns.str.replace(" ", "_")

In [28]:
df.columns

Index(['CustomerId', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction_Score',
       'Card_Type', 'Point_Earned', 'Age_Group', 'Credit_Score_Group',
       'Balance_Category', 'Satisfaction_Level'],
      dtype='str')

In [10]:
df = df.drop(columns=['RowNumber', 'Surname'])

In [11]:
df.head()

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [12]:
df.dtypes

CustomerId              int64
CreditScore             int64
Geography                 str
Gender                    str
Age                     int64
Tenure                  int64
Balance               float64
NumOfProducts           int64
HasCrCard               int64
IsActiveMember          int64
EstimatedSalary       float64
Exited                  int64
Complain                int64
Satisfaction Score      int64
Card Type                 str
Point Earned            int64
dtype: object

In [13]:
df.isnull().sum()

CustomerId            0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
age_bins = [17, 30, 45, 60, 100]
age_labels = ['18-30 (Gənc)', '31-45 (Orta Yaş)', '46-60 (Böyük Yaş)', '60+ (Senior)']
df['Age_Group'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels)

In [16]:
cs_bins = [300, 579, 669, 739, 799, 850]
cs_labels = ['Poor', 'Fair', 'Good', 'Very Good', 'Exceptional']
df['Credit_Score_Group'] = pd.cut(df['CreditScore'], bins=cs_bins, labels=cs_labels)

In [18]:
df['Balance_Category'] = np.where(df['Balance'] == 0, 'Zero Balance', 'Has Balance')

In [29]:
sat_map = {1: 'Very Low', 2: 'Low', 3: 'Medium', 4: 'High', 5: 'Very High'}
df['Satisfaction_Level'] = df['Satisfaction_Score'].map(sat_map)

In [30]:
df.head()

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction_Score,Card_Type,Point_Earned,Age_Group,Credit_Score_Group,Balance_Category,Satisfaction_Level
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464,31-45 (Orta Yaş),Fair,Zero Balance,Low
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456,31-45 (Orta Yaş),Fair,Has Balance,Medium
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377,31-45 (Orta Yaş),Poor,Has Balance,Medium
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350,31-45 (Orta Yaş),Good,Zero Balance,Very High
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425,31-45 (Orta Yaş),Exceptional,Has Balance,Very High

In [31]:
df.to_csv("cleaned_churn_data.csv", index=False)

In [25]:
numerical_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'EstimatedSalary', 'Point Earned']

print("--- Outlier Analizi (IQR Metodu) ---")
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"{col} sütunundakı outlier sayı: {len(outliers)}")

--- Outlier Analizi (IQR Metodu) ---
CreditScore sütunundakı outlier sayı: 15
Age sütunundakı outlier sayı: 359
Tenure sütunundakı outlier sayı: 0
Balance sütunundakı outlier sayı: 0
EstimatedSalary sütunundakı outlier sayı: 0
Point Earned sütunundakı outlier sayı: 0

In [3]:
import pandas as pd
from sqlalchemy import create_engine, text


df = pd.read_csv('Customer-Churn-Records.csv')


engine = create_engine('postgresql://postgres:admin123@localhost:5432/churn_db')


temp_df = df[['CustomerId', 'NumOfProducts']]
temp_df.to_sql('temp_num_products', engine, if_exists='replace', index=False)


with engine.begin() as conn:
    conn.execute(text("""
        UPDATE dim_customer d
        SET numofproducts = t."NumOfProducts"
        FROM temp_num_products t
        WHERE d.customer_id = t."CustomerId";
    """))
    conn.execute(text("DROP TABLE temp_num_products;"))

print("`numofproducts` sütunu uğurla `dim_customer` cədvəlinə əlavə olundu!")

`numofproducts` sütunu uğurla `dim_customer` cədvəlinə əlavə olundu!